import type { PosterTemplateDefinition } from '../../templateTypes';

export const businessAnnouncementTemplate: PosterTemplateDefinition = {
  id: 'bundled-business-announcement',
  name: 'Business announcement',
  category: 'business',
  description: 'Clean light layout for launches, openings, or company updates.',
  fields: [
    { key: 'eventTitle', label: 'Title / headline', sourceElementId: 'biz_title' },
    { key: 'tagline', label: 'Tagline / subtitle', sourceElementId: 'biz_tag' },
    { key: 'themeLine', label: 'Theme / motto', sourceElementId: 'biz_theme' },
    { key: 'dateTime', label: 'Date & time', sourceElementId: 'biz_when' },
    { key: 'venue', label: 'Venue / location', sourceElementId: 'biz_where' },
    { key: 'contactInfo', label: 'Contact / website', sourceElementId: 'biz_contact' },
  ],
  project: {
    canvasWidth: 800,
    canvasHeight: 600,
    canvasBackground: { type: 'solid', color: '#f8fafc' },
    elements: [
      {
        id: 'biz_bar',
        type: 'rect',
        left: 60,
        top: 100,
        width: 6,
        height: 200,
        fill: '#0f172a',
        rx: 2,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 1,
      },
      {
        id: 'biz_title',
        type: 'text',
        left: 100,
        top: 100,
        text: '{{eventTitle}}',
        fontSize: 48,
        fontFamily: 'system-ui, sans-serif',
        fill: '#0f172a',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 2,
      },
      {
        id: 'biz_tag',
        type: 'text',
        left: 100,
        top: 180,
        text: '{{tagline}}',
        fontSize: 20,
        fontFamily: 'system-ui, sans-serif',
        fill: '#475569',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 3,
      },
      {
        id: 'biz_theme',
        type: 'text',
        left: 100,
        top: 240,
        text: '{{themeLine}}',
        fontSize: 16,
        fontFamily: 'system-ui, sans-serif',
        fill: '#64748b',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 4,
      },
      {
        id: 'biz_when',
        type: 'text',
        left: 100,
        top: 320,
        text: '{{dateTime}}',
        fontSize: 18,
        fontFamily: 'system-ui, sans-serif',
        fill: '#0f172a',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 5,
      },
      {
        id: 'biz_where',
        type: 'text',
        left: 100,
        top: 355,
        text: '{{venue}}',
        fontSize: 16,
        fontFamily: 'system-ui, sans-serif',
        fill: '#475569',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 6,
      },
      {
        id: 'biz_contact',
        type: 'text',
        left: 100,
        top: 480,
        text: '{{contactInfo}}',
        fontSize: 15,
        fontFamily: 'system-ui, sans-serif',
        fill: '#64748b',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 7,
      },
    ],
  },
};
