import type { PosterTemplateDefinition } from '../../templateTypes';

export const churchEventTemplate: PosterTemplateDefinition = {
  id: 'bundled-church-event',
  name: 'Church gathering',
  category: 'church',
  description: 'Warm gradient header area with service title, theme verse line, and details.',
  fields: [
    { key: 'eventTitle', label: 'Title / headline', sourceElementId: 'ch_title' },
    { key: 'themeLine', label: 'Theme / verse / motto', sourceElementId: 'ch_theme' },
    { key: 'tagline', label: 'Tagline / subtitle', sourceElementId: 'ch_tag' },
    { key: 'dateTime', label: 'Date & time', sourceElementId: 'ch_when' },
    { key: 'venue', label: 'Venue / location', sourceElementId: 'ch_where' },
    { key: 'host', label: 'Host / organizer', sourceElementId: 'ch_host' },
    { key: 'guestName', label: 'Guest / speaker', sourceElementId: 'ch_guest' },
  ],
  project: {
    canvasWidth: 800,
    canvasHeight: 600,
    canvasBackground: {
      type: 'linear',
      angle: 160,
      stops: [
        { offset: 0, color: '#1e3a8a' },
        { offset: 0.5, color: '#4c1d95' },
        { offset: 1, color: '#312e81' },
      ],
    },
    elements: [
      {
        id: 'ch_rect_soft',
        type: 'rect',
        left: 40,
        top: 80,
        width: 720,
        height: 440,
        fill: { type: 'solid', color: 'rgba(255,255,255,0.08)' },
        rx: 16,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 1,
      },
      {
        id: 'ch_title',
        type: 'text',
        left: 72,
        top: 140,
        text: '{{eventTitle}}',
        fontSize: 44,
        fontFamily: 'Georgia, serif',
        fill: '#fefce8',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 2,
      },
      {
        id: 'ch_theme',
        type: 'text',
        left: 72,
        top: 210,
        text: '{{themeLine}}',
        fontSize: 20,
        fontFamily: 'Georgia, serif',
        fill: '#fde68a',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 3,
      },
      {
        id: 'ch_tag',
        type: 'text',
        left: 72,
        top: 270,
        text: '{{tagline}}',
        fontSize: 18,
        fontFamily: 'system-ui, sans-serif',
        fill: '#e0e7ff',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 4,
      },
      {
        id: 'ch_when',
        type: 'text',
        left: 72,
        top: 340,
        text: '{{dateTime}}',
        fontSize: 22,
        fontFamily: 'system-ui, sans-serif',
        fill: '#ffffff',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 5,
      },
      {
        id: 'ch_where',
        type: 'text',
        left: 72,
        top: 380,
        text: '{{venue}}',
        fontSize: 18,
        fontFamily: 'system-ui, sans-serif',
        fill: '#c7d2fe',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 6,
      },
      {
        id: 'ch_host',
        type: 'text',
        left: 72,
        top: 440,
        text: 'With {{host}}',
        fontSize: 16,
        fontFamily: 'system-ui, sans-serif',
        fill: '#a5b4fc',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 7,
      },
      {
        id: 'ch_guest',
        type: 'text',
        left: 72,
        top: 470,
        text: 'Guest: {{guestName}}',
        fontSize: 16,
        fontFamily: 'system-ui, sans-serif',
        fill: '#a5b4fc',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 8,
      },
    ],
  },
};
