import type { PosterTemplateDefinition } from '../../templateTypes';

export const conferenceSimpleTemplate: PosterTemplateDefinition = {
  id: 'bundled-conference-simple',
  name: 'Conference hero',
  category: 'conference',
  description: 'Bold title with date, venue, and speakers — good for tech or business summits.',
  fields: [
    { key: 'eventTitle', label: 'Title / headline', sourceElementId: 't_title' },
    { key: 'tagline', label: 'Tagline / subtitle', sourceElementId: 't_tagline' },
    { key: 'dateTime', label: 'Date & time', sourceElementId: 't_datetime' },
    { key: 'venue', label: 'Venue / location', sourceElementId: 't_venue' },
    { key: 'host', label: 'Host / organizer', sourceElementId: 't_host' },
    { key: 'guestName', label: 'Guest / speaker', sourceElementId: 't_guest' },
    { key: 'contactInfo', label: 'Contact / RSVP / website', sourceElementId: 't_contact' },
  ],
  project: {
    canvasWidth: 800,
    canvasHeight: 600,
    canvasBackground: { type: 'solid', color: '#0f172a' },
    elements: [
      {
        id: 't_rect_accent',
        type: 'rect',
        left: 0,
        top: 0,
        width: 800,
        height: 12,
        fill: '#f59e0b',
        rx: 0,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 1,
      },
      {
        id: 't_title',
        type: 'text',
        left: 72,
        top: 120,
        text: '{{eventTitle}}',
        fontSize: 52,
        fontFamily: 'Georgia, serif',
        fill: '#f8fafc',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 2,
      },
      {
        id: 't_tagline',
        type: 'text',
        left: 72,
        top: 200,
        text: '{{tagline}}',
        fontSize: 22,
        fontFamily: 'system-ui, sans-serif',
        fill: '#cbd5e1',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 3,
      },
      {
        id: 't_datetime',
        type: 'text',
        left: 72,
        top: 300,
        text: '{{dateTime}}',
        fontSize: 20,
        fontFamily: 'system-ui, sans-serif',
        fill: '#fbbf24',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 4,
      },
      {
        id: 't_venue',
        type: 'text',
        left: 72,
        top: 340,
        text: '{{venue}}',
        fontSize: 18,
        fontFamily: 'system-ui, sans-serif',
        fill: '#e2e8f0',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 5,
      },
      {
        id: 't_host',
        type: 'text',
        left: 400,
        top: 400,
        text: 'Hosted by {{host}}',
        fontSize: 16,
        fontFamily: 'system-ui, sans-serif',
        fill: '#94a3b8',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 6,
      },
      {
        id: 't_guest',
        type: 'text',
        left: 72,
        top: 430,
        text: 'Featuring {{guestName}}',
        fontSize: 16,
        fontFamily: 'system-ui, sans-serif',
        fill: '#94a3b8',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 7,
      },
      {
        id: 't_contact',
        type: 'text',
        left: 72,
        top: 540,
        text: '{{contactInfo}}',
        fontSize: 14,
        fontFamily: 'system-ui, sans-serif',
        fill: '#64748b',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 8,
      },
    ],
  },
};
