import type { PosterTemplateDefinition } from '../../templateTypes';

export const genericEventTemplate: PosterTemplateDefinition = {
  id: 'bundled-event-simple',
  name: 'Event flyer',
  category: 'event',
  description: 'Playful block layout for parties, fundraisers, and community events.',
  fields: [
    { key: 'eventTitle', label: 'Title / headline', sourceElementId: 'ev_title' },
    { key: 'tagline', label: 'Tagline / subtitle', sourceElementId: 'ev_tag' },
    { key: 'dateTime', label: 'Date & time', sourceElementId: 'ev_when' },
    { key: 'venue', label: 'Venue / location', sourceElementId: 'ev_where' },
    { key: 'themeLine', label: 'Theme / motto', sourceElementId: 'ev_line' },
    { key: 'contactInfo', label: 'Contact / RSVP', sourceElementId: 'ev_rsvp' },
  ],
  project: {
    canvasWidth: 800,
    canvasHeight: 600,
    canvasBackground: {
      type: 'radial',
      cx: 0.5,
      cy: 0.35,
      r: 0.85,
      stops: [
        { offset: 0, color: '#fef3c7' },
        { offset: 1, color: '#f59e0b' },
      ],
    },
    elements: [
      {
        id: 'ev_circle',
        type: 'circle',
        left: 620,
        top: 80,
        radius: 70,
        fill: '#ffffff',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 0.35,
        zIndex: 1,
      },
      {
        id: 'ev_title',
        type: 'text',
        left: 64,
        top: 100,
        text: '{{eventTitle}}',
        fontSize: 46,
        fontFamily: 'system-ui, sans-serif',
        fill: '#78350f',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 2,
      },
      {
        id: 'ev_tag',
        type: 'text',
        left: 64,
        top: 175,
        text: '{{tagline}}',
        fontSize: 22,
        fontFamily: 'system-ui, sans-serif',
        fill: '#92400e',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 3,
      },
      {
        id: 'ev_when',
        type: 'text',
        left: 64,
        top: 280,
        text: '{{dateTime}}',
        fontSize: 24,
        fontFamily: 'system-ui, sans-serif',
        fill: '#451a03',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 4,
      },
      {
        id: 'ev_where',
        type: 'text',
        left: 64,
        top: 325,
        text: '{{venue}}',
        fontSize: 20,
        fontFamily: 'system-ui, sans-serif',
        fill: '#78350f',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 5,
      },
      {
        id: 'ev_line',
        type: 'text',
        left: 64,
        top: 400,
        text: '{{themeLine}}',
        fontSize: 18,
        fontFamily: 'Georgia, serif',
        fill: '#451a03',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 6,
      },
      {
        id: 'ev_rsvp',
        type: 'text',
        left: 64,
        top: 520,
        text: '{{contactInfo}}',
        fontSize: 16,
        fontFamily: 'system-ui, sans-serif',
        fill: '#92400e',
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        opacity: 1,
        zIndex: 7,
      },
    ],
  },
};
